//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportApp.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportPage
    {
        public int Id { get; set; }
        public int Subject_Id { get; set; }
        public int Student_Id { get; set; }
        public bool Presence { get; set; }
        public int DayInfoId { get; set; }
    
        public virtual DayInfo DayInfo { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
